name: Rails Unit Tests

on: [push, pull_request]

jobs:
  brakeman:
    name: runner / brakeman
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: brakeman
        uses: reviewdog/action-brakeman@v1
        with:
          brakeman_version: 4.8.2
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Default is github-pr-check
